name: Build binary wheel

on: [pull_request,push]
jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest]
        # python-version: [3.6, 3.7, 3.7]
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install
      run: |
        python -m pip install cibuildwheel==1.3.0


    - name: Build
      env:
        CIBW_BEFORE_BUILD: pip install pybind11 pyarrow
        CIBW_BUILD: cp37*64
      run: |
        python -m cibuildwheel --output-dir dist

    - name: Test
      shell: bash
      run: |
        ls -alh
        ls -alh dist
        rm -rf vaex_arrow_ext
        pip install dist/*
        pip install ${{ matrix.test-wheel }} pytest
        python test_ext.py
        pytest -v -s

    - uses: actions/upload-artifact@v1
      with:
        name: distributions
        path: ./dist

